# Generated by Django 4.0.2 on 2022-11-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jkk',
            old_name='timejkk',
            new_name='xarray',
        ),
    ]
