# Generated by Django 4.0.2 on 2022-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0002_rename_timejkk_jkk_xarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkk',
            name='xarray',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
