# Generated by Django 4.0.2 on 2022-11-12 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0003_alter_jkk_xarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkk',
            name='xarray',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
