# Generated by Django 4.0.2 on 2022-11-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0004_alter_jkk_xarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkk',
            name='xarray',
            field=models.CharField(max_length=200),
        ),
    ]
