# Generated by Django 4.0.2 on 2022-11-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0006_rename_xarray_jkk_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jkk',
            old_name='x',
            new_name='xelement',
        ),
    ]
