# Generated by Django 4.0.2 on 2022-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0007_rename_x_jkk_xelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkk',
            name='element1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jkk',
            name='element2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jkk',
            name='element3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
