# Generated by Django 4.0.2 on 2022-11-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0008_jkk_element1_jkk_element2_jkk_element3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
