# Generated by Django 4.0.2 on 2022-11-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0010_alter_process_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepnumber', models.IntegerField()),
                ('mayor_element', models.CharField(max_length=300)),
                ('keypoint', models.CharField(max_length=300)),
                ('worktime', models.IntegerField()),
                ('walktime', models.IntegerField()),
                ('tolerance', models.FloatField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.process')),
            ],
        ),
    ]
