# Generated by Django 4.0.2 on 2022-11-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0011_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyJkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dailyprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.process')),
            ],
        ),
        migrations.DeleteModel(
            name='Jkk',
        ),
    ]
