# Generated by Django 4.0.2 on 2022-11-14 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0012_dailyjkk_delete_jkk'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodJkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team_member', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('jkk_dayly_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.dailyjkk')),
            ],
        ),
    ]
