# Generated by Django 4.0.2 on 2022-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0013_periodjkk'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=6)),
            ],
        ),
    ]
