# Generated by Django 4.0.2 on 2022-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0014_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='employeeid',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
