# Generated by Django 4.0.2 on 2022-11-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0015_alter_teammember_employeeid_alter_teammember_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='periodjkk',
            name='team_member',
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='jkk_dayly_tm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jkk.teammember'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodjkk',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.teamoff'),
        ),
    ]
