# Generated by Django 4.0.2 on 2022-11-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0016_teamoff_remove_periodjkk_team_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyjkk',
            name='dayadh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='periodadh',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='checkJkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timecheck', models.FloatField()),
                ('checkstatus', models.BooleanField(null=True)),
                ('jkk_elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.elements')),
                ('periodjkkcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.dailyjkk')),
            ],
        ),
    ]
