# Generated by Django 4.0.2 on 2022-11-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0019_stopwatch_delete_checkjkk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teamoff',
            new_name='teamleader',
        ),
        migrations.CreateModel(
            name='checkJkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timecheck', models.FloatField()),
                ('checkstatus', models.BooleanField(null=True)),
                ('checkelements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.elements')),
                ('periodjkkcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jkk.dailyjkk')),
            ],
        ),
    ]
