# Generated by Django 4.0.2 on 2022-11-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0020_rename_teamoff_teamleader_checkjkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodjkk',
            name='periodadh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
