# Generated by Django 4.0.2 on 2022-11-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0021_alter_periodjkk_periodadh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dailyJkk',
            new_name='Jkk',
        ),
        migrations.RenameField(
            model_name='periodjkk',
            old_name='jkk_dayly_process',
            new_name='jkk_process',
        ),
        migrations.RenameField(
            model_name='periodjkk',
            old_name='jkk_dayly_tm',
            new_name='jkk_tm',
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='checkelements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jkk.elements'),
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='checkstatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='name',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], default='1', help_text='Period select', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodjkk',
            name='timecheck',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodjkk',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jkk.teamleader'),
        ),
        migrations.DeleteModel(
            name='checkJkk',
        ),
    ]
