# Generated by Django 4.0.2 on 2022-11-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0022_rename_dailyjkk_jkk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodjkk',
            name='jkk_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jkk.jkk'),
        ),
        migrations.AlterField(
            model_name='periodjkk',
            name='timecheck',
            field=models.FloatField(null=True),
        ),
    ]
