# Generated by Django 4.0.2 on 2022-11-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0023_alter_periodjkk_jkk_process_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodjkk',
            old_name='name',
            new_name='period_sel',
        ),
    ]
