# Generated by Django 4.0.2 on 2022-11-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0025_jkks8_remove_elements_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_4',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_5',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='step_2',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='step_3',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='step_4',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='step_5',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_4',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_5',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptol_1',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptol_2',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptol_3',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptol_4',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptol_5',
        ),
    ]
