# Generated by Django 4.0.2 on 2022-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0027_s8elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_10',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_11',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_12',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_13',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_14',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_15',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_4',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_5',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_6',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_7',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_8',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='checkstatus_9',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='comment_step',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jkks8',
            name='steptime_9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
