# Generated by Django 4.0.2 on 2022-11-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0029_teammember_alter_jkks8_jkk_tm'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='jkks8',
            name='jkk_auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jkk.teamleader'),
        ),
    ]
