# Generated by Django 4.0.2 on 2022-11-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0030_teamleader_alter_jkks8_jkk_auditor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jkks8',
            old_name='jkk_tm',
            new_name='jkk_teammember',
        ),
    ]
