# Generated by Django 4.0.2 on 2022-11-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0031_rename_jkk_tm_jkks8_jkk_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jkks8',
            old_name='comment_step',
            new_name='step_number',
        ),
    ]
