# Generated by Django 4.0.2 on 2022-11-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0032_rename_comment_step_jkks8_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkks8',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
