# Generated by Django 4.0.2 on 2022-12-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0033_alter_jkks8_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_10',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_11',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_12',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_13',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_14',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_15',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_7',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_8',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='checkstatus_9',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_10',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_11',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_12',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_13',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_14',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_15',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_7',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_8',
        ),
        migrations.RemoveField(
            model_name='jkks8',
            name='steptime_9',
        ),
    ]
