# Generated by Django 4.0.2 on 2022-12-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkk', '0034_remove_jkks8_checkstatus_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkks8',
            name='sumelemtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
